from typing import Protocol

from src.knowledge_extension.assets.models import AssetQuery, AssetWriteResult, KnowledgeAsset, KnowledgeChunk


class KnowledgeAssetRepository(Protocol):
    def add_asset(self, asset: KnowledgeAsset) -> AssetWriteResult: ...
    def get_asset(self, asset_id: str) -> KnowledgeAsset: ...
    def list_assets(self, query: AssetQuery) -> list[KnowledgeAsset]: ...


class KnowledgeChunkRepository(Protocol):
    def add_chunk(self, chunk: KnowledgeChunk) -> AssetWriteResult: ...
    def list_chunks(self, query: AssetQuery) -> list[KnowledgeChunk]: ...
