from typing import Protocol

from src.data_platform.storage.skill.models import SkillStorageHealth
from src.domain.skill.models import Skill


class SkillStorage(Protocol):
    def save_skill(self, skill: Skill) -> None: ...

    def get_skill(self, skill_id: str) -> Skill | None: ...

    def list_skills(self) -> list[Skill]: ...

    def list_skills_by_owner(self, owner: str) -> list[Skill]: ...

    def list_skills_by_role(self, role: str) -> list[Skill]: ...

    def delete_skill(self, skill_id: str) -> bool: ...

    def health(self) -> SkillStorageHealth: ...
