"""数据模型存储端口 — 架构设计 V3.0 §4.2。

遵循项目 ports/adapter 模式：in_memory（开发/测试，USE_MEMORY_STORAGE=1）
与 postgres 双实现。模型文档 JSONB 整体存储（与 governed_flows 同模式）；
映射独立成行——确认流（Slice 4）按 (model, field, source) 粒度单独确认。
"""
from typing import Protocol

from src.domain.data_model.models import DataModel, DataModelMapping


class DataModelStorage(Protocol):
    """数据模型主表 + 多源映射的存储契约（乐观锁 revision 比较-交换）。"""

    def create_model(self, model: DataModel) -> DataModel: ...
    def get_model(self, model_code: str) -> DataModel | None: ...
    def list_models(self) -> list[DataModel]: ...
    def update_model(self, model: DataModel, expected_revision: int) -> DataModel: ...
    def delete_model(self, model_code: str, expected_revision: int) -> None: ...

    def upsert_mapping(self, mapping: DataModelMapping, expected_revision: int | None) -> DataModelMapping: ...
    def list_mappings(self, model_code: str) -> list[DataModelMapping]: ...
    def get_mapping(self, model_code: str, field_code: str, source_id: str) -> DataModelMapping | None: ...
    def delete_mapping(self, model_code: str, field_code: str, source_id: str, expected_revision: int) -> None: ...
