from typing import Protocol

from src.data_platform.storage.mcp.models import McpStorageHealth
from src.knowledge_extension.mcp_registry.models import McpCapability, McpServer


class McpStorage(Protocol):
    def save_server(self, server: McpServer) -> None: ...

    def get_server(self, server_id: str) -> McpServer | None: ...

    def list_servers(self) -> list[McpServer]: ...

    def save_capability(self, capability: McpCapability) -> None: ...

    def get_capability(self, capability_id: str) -> McpCapability | None: ...

    def list_capabilities(self) -> list[McpCapability]: ...

    def health(self) -> McpStorageHealth: ...
