"""治理 Flow 存储端口 — Phase 1。

遵循项目 ports/adapter 模式（照 skill 版本存储四件套）：
in_memory（开发/测试，USE_MEMORY_STORAGE=1）与 postgres 双实现。
"""
from typing import Protocol

from src.domain.governed_flow.models import FlowDefinition, FlowPublishedRevision


class GovernedFlowStorage(Protocol):
    """Flow 草稿主表 + 不可变发布版本证据的存储契约。"""

    def create_flow(self, flow: FlowDefinition) -> FlowDefinition: ...
    def get_flow(self, flow_id: str) -> FlowDefinition | None: ...
    def list_flows(self) -> list[FlowDefinition]: ...
    def update_flow(self, flow: FlowDefinition, expected_revision: int) -> FlowDefinition: ...
    def delete_flow(self, flow_id: str, expected_revision: int) -> None: ...

    def save_published_revision(self, revision: FlowPublishedRevision) -> None: ...
    def get_published_revision(self, revision_id: str) -> FlowPublishedRevision | None: ...
    def list_published_revisions(self, flow_id: str) -> list[FlowPublishedRevision]: ...
    def get_active_revision(self, flow_id: str) -> FlowPublishedRevision | None: ...
    def set_active_revision(self, flow_id: str, revision_id: str) -> None: ...
